# Copyright (C) 2021-2026 Manuele Conti
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate portable C code from the analyzed Structured Text AST."""

import re

from .visitor import NodeVisitor
from ..runtime.loader import render_primitives


class CCodeGenerator(NodeVisitor):
    def __init__(self, context=None, source_name="<stdin>", native_implementations=None):
        self.context = context
        self.source_name = source_name
        self.native_implementations = native_implementations or {}
        display_source = str(source_name).replace("*/", "* /")
        standard_edition = context.standard_edition if context is not None else 3
        self.text = (
            "/*\n"
            " * Portable C generated by STC.\n"
            f" * Source: {display_source}\n"
            f" * IEC profile: IEC 61131-3 Edition {standard_edition}\n"
            " *\n"
            " * This file contains the translated IEC 61131-3 program and its runtime glue.\n"
            " * Regenerate it from the Structured Text source instead of editing it directly.\n"
            " */\n\n"
            "/* Standard C library headers. */\n"
            "#include <stdbool.h>\n"
            "#include <stdint.h>\n"
            "#include <math.h>\n"
            "#include <stdio.h>\n"
            "#include <stdlib.h>\n"
            "#include <string.h>\n\n"
        )
        self.indent = ""
        self.current_function = None
        self.current_return_type = None
        self.current_instance = None
        self.current_instance_fields = set()
        self.current_pointer_params = set()
        self._types_pre_emitted = False

    def iecType2C(self, typein):
        conv = {
            "SINT": "int8_t", "INT": "int16_t", "DINT": "int32_t", "LINT": "int64_t",
            "USINT": "uint8_t", "UINT": "uint16_t", "UDINT": "uint32_t", "ULINT": "uint64_t",
            "REAL": "float", "LREAL": "double",
            "BOOL": "bool", "BYTE": "uint8_t", "WORD": "uint16_t", "DWORD": "uint32_t",
            "LWORD": "uint64_t", "TIME": "int64_t", "DATE": "int64_t",
            "LTIME": "int64_t", "LDATE": "int64_t", "LTOD": "int64_t", "LDT": "int64_t",
            "TIME_OF_DAY": "int64_t", "TOD": "int64_t", "DATE_AND_TIME": "int64_t",
            "DT": "int64_t", "CHAR": "uint8_t", "WCHAR": "uint16_t", "UCHAR": "uint32_t",
            "STRING": "const char *", "WSTRING": "const char *", "USTRING": "const char *",
        }
        return conv.get(typein.upper(), typein)


    def c_type_for_node(self, node, fallback=None):
        if self.context is not None:
            datatype = self.context.type_of(node)
            if datatype is not None and datatype.name not in {"<unknown>", "<error>"}:
                return self.iecType2C(datatype.name)
        return fallback

    def source_line_directive(self, node):
        if self.context is None or self.context.source_map is None:
            return ""
        span = self.context.source_map.span_for(node)
        if span is None or self.source_name in {"-", "<stdin>"}:
            return ""
        escaped = self.source_name.replace("\\", "\\\\").replace('"', '\\"')
        return f'#line {span.start_line} "{escaped}"\n'

    def indent_inc(self):
        self.indent += "    "

    def indent_dec(self):
        self.indent = self.indent[:-4]

    def render(self, node):
        previous = self.text
        self.text = ""
        self.visit(node)
        rendered = self.text
        self.text = previous
        return rendered

    def extract_type(self, node):
        if isinstance(node, dict):
            if node.get("name", "").endswith("_type_name") and node.get("value"):
                return self.iecType2C(node["value"])
            for child in node.get("children", []):
                found = self.extract_type(child)
                if found:
                    return found
        return None

    def declaration_type(self, node, fallback="int16_t"):
        """Return a target type for an IEC declaration, including strings."""
        if self._first_named(node, "single_byte_string_spec") is not None:
            return "const char *"
        if self._first_named(node, "double_byte_string_spec") is not None:
            return "const char *"
        found = self.extract_type(node)
        if found:
            return found
        raw_types = {value.upper() for value in self._raw_values(node) if isinstance(value, str)}
        for type_name in ("STRING", "WSTRING", "USTRING", "CHAR", "WCHAR", "UCHAR",
                          "TIME", "LTIME", "DATE", "LDATE", "TOD", "LTOD", "TIME_OF_DAY", "DT", "LDT", "DATE_AND_TIME"):
            if type_name in raw_types:
                return self.iecType2C(type_name)
        return fallback

    def _raw_values(self, node):
        if isinstance(node, str):
            yield node
        elif isinstance(node, dict):
            value = node.get("value")
            if isinstance(value, str):
                yield value
            for child in node.get("children", []):
                yield from self._raw_values(child)

    def _string_max_length(self, expression):
        """Return the declared maximum length of an IEC string expression."""
        if expression is None or self.context is None:
            return None
        variable = self._first_named(expression, "variable_name")
        if variable is None:
            return None
        symbol = self.context.symbols.symbol_for_reference(variable)
        if symbol is None or symbol.type_ref.name is None:
            return None
        type_name = str(symbol.type_ref.name or "").upper()
        if type_name not in {"STRING", "WSTRING", "USTRING"}:
            return None
        # For STRING[n], WSTRING[n] and USTRING[n], TypeRef.node still
        # contains the original declaration AST, including integer n.
        declaration = symbol.type_ref.node
        size = self._first_named(declaration, "integer")
        if size is not None and size.get("value") is not None:
            return int(str(size["value"]).replace("_", ""))
        # IEC default maximum length when no explicit [n] is supplied.
        return 80

    def zero_value(self, c_type):
        if c_type == "bool":
            return "false"
        if c_type == "float":
            return "0.0f"
        if c_type == "double":
            return "0.0"
        if c_type == "const char *":
            return "NULL"
        return "0"

    def _array_dimensions(self, specification):
        dimensions = []
        for range_node in self._named_nodes(specification, "subrange"):
            bounds = self._named_nodes(range_node, "signed_integer")
            if len(bounds) == 2:
                lower, upper = self.render(bounds[0]), self.render(bounds[1])
                dimensions.append(f"[{upper} - ({lower}) + 1]")
        return "".join(dimensions)

    def _declaration_type(self, node):
        if self._first_named(node, "single_byte_string_spec") is not None:
            return "const char *"
        if self._first_named(node, "double_byte_string_spec") is not None:
            return "const char *"
        array = self._first_named(node, "array_specification")
        if array is not None:
            named = self._first_named(array, "array_type_name")
            if named is not None:
                return named["value"]
            return self.declaration_type(array) + self._array_dimensions(array)
        for kind in ("structure_type_name", "function_block_type_name"):
            named = self._first_named(node, kind)
            if named is not None:
                value = named.get("value")
                if value:
                    return self.iecType2C(value)
                leaf = next((item.get("value") for item in self._named_nodes(named, "standard_function_block_name") if item.get("value")), None)
                if leaf:
                    return leaf
                leaf = next((item.get("value") for item in self._named_nodes(named, "derived_function_block_name") if item.get("value")), None)
                if leaf:
                    return leaf
        return self.declaration_type(node)

    @staticmethod
    def _format_declarator(var_type, name, pointer=False):
        bracket = var_type.find("[")
        if bracket >= 0:
            base, dimensions = var_type[:bracket], var_type[bracket:]
            return f"{base} (*{name}){dimensions}" if pointer else f"{base} {name}{dimensions}"
        if pointer:
            separator = "" if var_type.rstrip().endswith("*") else " "
            return f"{var_type}{separator}*{name}"
        separator = "" if var_type.rstrip().endswith("*") else " "
        return f"{var_type}{separator}{name}"

    def _emit_section(self, title):
        self.text += f"/* --- {title} " + "-" * max(1, 68 - len(title)) + " */\n\n"

    def collect_var_decls(self, node):
        declarations = []
        if not isinstance(node, dict):
            return declarations
        declaration_nodes = {
            "var1_init_decl", "var1_declaration", "array_var_init_decl",
            "array_var_declaration", "structured_var_init_decl", "structured_var_declaration",
            "string_var_declaration", "fb_name_decl", "located_var_decl",
        }
        if node.get("name") in declaration_nodes:
            names = []
            for child in self._named_nodes(node, "variable_name"):
                if child.get("value") and child["value"] not in names:
                    names.append(child["value"])
            if not names:
                for child in self._named_nodes(node, "fb_name"):
                    if child.get("value") and child["value"] not in names:
                        names.append(child["value"])
            var_type = self._declaration_type(node)
            declarations.extend((var_type, name) for name in names)
            return declarations
        for child in node.get("children", []):
            declarations.extend(self.collect_var_decls(child))
        return declarations

    def _section_declarations(self, node):
        declarations = []
        for section in ("input_declarations", "output_declarations", "input_output_declarations",
                        "var_declarations", "retentive_var_declarations", "non_retentive_var_decls",
                        "temp_var_decls", "function_var_decls"):
            declarations.extend(self.collect_sections(node, section))
        return declarations

    def _persistent_declarations(self, node):
        declarations = []
        for section in ("input_declarations", "output_declarations", "input_output_declarations",
                        "var_declarations", "retentive_var_declarations", "non_retentive_var_decls"):
            declarations.extend(self.collect_sections(node, section))
        return declarations

    def _temporary_declarations(self, node):
        return self.collect_sections(node, "temp_var_decls")

    def _retained_declarations(self, node):
        return self.collect_sections(node, "retentive_var_declarations")

    def _declaration_initializers(self, node):
        result = {}
        declaration_nodes = {
            "var1_init_decl", "string_var_declaration",
        }
        persistent_sections = {
            "input_declarations", "output_declarations", "input_output_declarations",
            "var_declarations", "retentive_var_declarations", "non_retentive_var_decls",
        }
        for section_name in persistent_sections:
            for section in self._named_nodes(node, section_name):
                for declaration in self._iter_named_set(section, declaration_nodes):
                    initializer = self._first_named(declaration, "constant")
                    if initializer is None:
                        continue
                    value = self.render(initializer)
                    for var_type, field in self.collect_var_decls(declaration):
                        if "[" not in var_type:
                            result[field.casefold()] = value
        return result

    def _iter_named_set(self, node, names):
        if not isinstance(node, dict):
            return
        if node.get("name") in names:
            yield node
            return
        for child in node.get("children", []):
            yield from self._iter_named_set(child, names)

    @staticmethod
    def _unique_declarations(declarations):
        result = []
        seen = set()
        for declaration in declarations:
            key = declaration[1].casefold()
            if key not in seen:
                seen.add(key)
                result.append(declaration)
        return result

    def _emit_instance_initializers(self, name, declarations, retained, initializers):
        retained_names = {field.casefold() for _, field in retained}
        self.text += "/* Reset all instance state for a cold start. */\n"
        self.text += f"void {name}_cold_init({name} *self)\n{{\n    memset(self, 0, sizeof(*self));\n"
        for _, field in declarations:
            if field.casefold() in initializers:
                self.text += f"    self->{field} = {initializers[field.casefold()]};\n"
        self.text += "}\n\n"
        self.text += "/* Reset non-retentive state while preserving RETAIN fields. */\n"
        self.text += f"void {name}_warm_init({name} *self)\n{{\n"
        if not declarations:
            self.text += "    (void)self;\n"
        for _, field in declarations:
            if field.casefold() not in retained_names:
                self.text += f"    memset(&self->{field}, 0, sizeof(self->{field}));\n"
                if field.casefold() in initializers:
                    self.text += f"    self->{field} = {initializers[field.casefold()]};\n"
        self.text += "}\n\n"

    def collect_sections(self, node, section_name):
        if not isinstance(node, dict):
            return []
        if node.get("name") == section_name:
            return self.collect_var_decls(node)
        declarations = []
        for child in node.get("children", []):
            declarations.extend(self.collect_sections(child, section_name))
        return declarations

    def visit_integer_literal(self, node):
        self.text += node["value"].replace("_", "")

    def visit_real_literal(self, node):
        value = node["value"].replace("_", "")
        c_type = self.c_type_for_node(node)
        if c_type == "float" and not value.lower().endswith("f"):
            value += "f"
        self.text += value

    def visit_integer(self, node):
        self.text += node["value"].replace("_", "")

    def visit_signed_integer(self, node):
        if node.get("value") is not None:
            self.text += str(node["value"]).replace("_", "")
        else:
            self.accept(node)

    def _visit_based_integer(self, node, base, prefix=""):
        value = self.render(node["children"][0]).replace("_", "")
        digits = value.split("#", 1)[-1]
        # C11 has no binary literal syntax, so binary values are emitted as
        # decimal. Octal and hexadecimal literals retain their readable form.
        self.text += str(int(digits, base)) if base == 2 else prefix + digits

    def visit_binary_integer(self, node):
        self._visit_based_integer(node, 2)

    def visit_octal_integer(self, node):
        self._visit_based_integer(node, 8, "0")

    def visit_hex_integer(self, node):
        self._visit_based_integer(node, 16, "0x")

    def visit_boolean_literal(self, node):
        self.text += node["value"].lower()

    def visit_bit_string_literal(self, node):
        for child in node["children"]:
            self.visit(child)

    def _iec_string(self, node):
        token = self._first_named(node, "token")
        raw = str(token.get("value", "''")) if token else "''"
        content = raw[1:-1] if len(raw) >= 2 else raw
        content = content.replace("$N", "\n").replace("$n", "\n")
        content = content.replace("$T", "\t").replace("$t", "\t")
        content = content.replace("$$", "$").replace("$''", "'").replace("$'", "'")
        content = content.replace("''", "'")
        content = content.replace("\\", "\\\\").replace('"', '\\"')
        content = content.replace("\n", "\\n").replace("\t", "\\t")
        return f'"{content}"'

    @staticmethod
    def _unicode_content(raw):
        """Decode the Edition 4 ${HEX} escape into a Unicode scalar value."""
        sharp = raw.find("#")
        quoted = raw[sharp + 1:].strip() if sharp >= 0 else raw
        content = quoted[1:-1] if len(quoted) >= 2 else quoted
        content = re.sub(
            r"\$\{([0-9A-Fa-f]{1,6})\}",
            lambda match: (
                chr(int(match.group(1), 16))
                if int(match.group(1), 16) <= 0x10FFFF
                and not 0xD800 <= int(match.group(1), 16) <= 0xDFFF
                else "\ufffd"
            ),
            content,
        )
        return content.replace("$N", "\n").replace("$n", "\n").replace("$$", "$").replace("''", "'")

    def visit_unicode_character_string(self, node):
        token = self._first_named(node, "token")
        raw = str(token.get("value", "U#''")) if token else "U#''"
        content = self._unicode_content(raw)
        if raw.lstrip().upper().startswith("UCHAR"):
            self.text += str(ord(content[0]) if content else 0)
            return
        escaped = content.replace("\\", "\\\\").replace('"', '\\"')
        escaped = escaped.replace("\n", "\\n").replace("\t", "\\t")
        self.text += f'"{escaped}"'

    @staticmethod
    def _typed_character_content(raw):
        quoted = raw[raw.find("#") + 1:].strip()
        content = quoted[1:-1] if len(quoted) >= 2 else quoted
        content = re.sub(
            r"\$([0-9A-Fa-f]{2}|[0-9A-Fa-f]{4})",
            lambda match: chr(int(match.group(1), 16)),
            content,
        )
        return content.replace("$N", "\n").replace("$n", "\n").replace("$T", "\t").replace("$t", "\t").replace("$$", "$").replace("''", "'").replace('""', '"')

    def visit_typed_character_string(self, node):
        token = self._first_named(node, "token")
        raw = str(token.get("value", "STRING#''")) if token else "STRING#''"
        prefix = raw[:raw.find("#")].strip().upper()
        content = self._typed_character_content(raw)
        if prefix in {"CHAR", "WCHAR"}:
            self.text += str(ord(content[0]) if content else 0)
            return
        escaped = content.replace("\\", "\\\\").replace('"', '\\"')
        escaped = escaped.replace("\n", "\\n").replace("\t", "\\t")
        self.text += f'"{escaped}"'

    def visit_single_byte_character_string(self, node):
        self.text += self._iec_string(node)

    def visit_double_byte_character_string(self, node):
        token = self._first_named(node, "token")
        raw = str(token.get("value", '""')) if token else '""'
        self.text += raw

    def visit_duration(self, node):
        multipliers = {"d": 86400000, "h": 3600000, "m": 60000, "s": 1000, "ms": 1}
        total = 0.0
        for component in self._named_nodes(node, "duration_component"):
            number = self._first_named(component, "integer") or self._first_named(component, "real_literal")
            tokens = self._named_nodes(component, "token")
            unit = str(tokens[-1].get("value", "ms")).casefold() if tokens else "ms"
            try:
                total += float(number.get("value", 0)) * multipliers.get(unit, 1)
            except (AttributeError, ValueError):
                pass
        self.text += str(int(total))

    def visit_date(self, node):
        values = [int(item.get("value", 0)) for item in self._named_nodes(node, "integer")]
        self.text += str(values[0] * 10000 + values[1] * 100 + values[2] if len(values) >= 3 else 0)

    def visit_time_of_day(self, node):
        values = [int(float(item.get("value", 0))) for item in self._named_nodes(node, "integer")]
        self.text += str(((values[0] * 60 + values[1]) * 60 + values[2]) * 1000 if len(values) >= 3 else 0)

    def visit_date_and_time(self, node):
        values = [int(float(item.get("value", 0))) for item in self._named_nodes(node, "integer")]
        if len(values) >= 6:
            self.text += str((((values[0] * 100 + values[1]) * 100 + values[2]) * 1000000) + values[3] * 10000 + values[4] * 100 + values[5])
        else:
            self.text += "0"

    def visit_signed_integer_type_name(self, node):
        self.text += self.iecType2C(node["value"])

    def visit_unsigned_integer_type_name(self, node):
        self.text += self.iecType2C(node["value"])

    def visit_real_type_name(self, node):
        self.text += self.iecType2C(node["value"])

    def visit_bit_string_type_name(self, node):
        self.text += self.iecType2C(node["value"])

    def visit_variable_name(self, node):
        name = node["value"]
        if self.current_instance is not None and name.casefold() in self.current_instance_fields:
            self.text += f"{self.current_instance}->{name}"
        elif name.casefold() in self.current_pointer_params:
            self.text += f"(*{name})"
        elif self.context is not None:
            symbol = self.context.symbols.symbol_for_reference(node)
            if symbol is not None and symbol.storage in {"output", "in_out"}:
                self.text += f"(*{name})"
            else:
                self.text += name
        else:
            self.text += name

    def visit_enumerated_value(self, node):
        self.text += str(node.get("value", "0"))

    def visit_qualified_enumerated_value(self, node):
        self.accept(node)

    def visit_field_selector(self, node):
        self.text += str(node.get("value", ""))

    def visit_subscript_list(self, node):
        for subscript in self._named_nodes(node, "subscript"):
            self.text += f"[{self.render(subscript)}]"

    def visit_library(self, node):
        self._emit_section("IEC 61131-3 runtime support")
        requested = {
            str(item.get("value", "")).upper()
            for item in self._named_nodes(node, "standard_function_name")
        }
        if self._named_nodes(node, "assert_statement"):
            requested.add("ASSERT")
        self.text += render_primitives("c", requested) + "\n"
        type_declarations = self._named_nodes(node, "data_type_declaration")
        if type_declarations:
            self._emit_section("User-defined IEC data types")
        for declaration in type_declarations:
            self.visit_data_type_declaration(declaration)
        self._types_pre_emitted = True
        if type_declarations:
            self.text += "\n"
        global_declarations = self._named_nodes(node, "global_var_decl")
        if global_declarations:
            self._emit_section("Configuration global variables")
        for global_decl in global_declarations:
            names = [item.get("value") for item in self._named_nodes(global_decl, "global_var_name") if item.get("value")]
            var_type = self._declaration_type(global_decl)
            section = self._ancestor_section(node, global_decl, "global_var_declarations")
            is_constant = section is not None and "CONSTANT" in {value.upper() for value in self._raw_values(section)}
            initializer = self._first_named(global_decl, "constant")
            initial_value = self.render(initializer) if initializer is not None else "0"
            for name in names:
                qualifier = "const " if is_constant else ""
                self.text += qualifier + self._format_declarator(var_type, name) + f" = {initial_value};\n"
        if global_declarations:
            self.text += "\n"
        declarations = list(self._function_declarations(node))
        if declarations:
            self._emit_section("Function declarations")
            for declaration in declarations:
                return_type, emitted_name, params = self._function_signature(declaration)
                self.text += f"{return_type} {emitted_name}({', '.join(params) or 'void'});\n"
            self.text += "\n"
        self._emit_section("Program organization unit implementations")
        self.accept(node, lambda name: name != "data_type_declaration")
        configurations = self._named_nodes(node, "configuration_declaration")
        if configurations:
            self.text += "\n/* Standalone entry point. Define STC_NO_MAIN when embedding this file. */\n"
            self.text += "\n#ifndef STC_NO_MAIN\nint main(void)\n{\n"
            for configuration in configurations:
                config_name = self._first_named(configuration, "configuration_name")["value"]
                self.text += f"    {config_name}_cold_start();\n    {config_name}_cycle({config_name}_base_interval_ms());\n"
            self.text += "    return 0;\n}\n#endif\n"

    def _ancestor_section(self, root, target, name):
        if not isinstance(root, dict):
            return None
        if root.get("name") == name and any(item is target for item in self._named_nodes(root, target.get("name"))):
            return root
        for child in root.get("children", []):
            found = self._ancestor_section(child, target, name)
            if found is not None:
                return found
        return None


    def _function_declarations(self, node):
        if not isinstance(node, dict):
            return
        if node.get("name") == "function_declaration":
            yield node
            return
        for child in node.get("children", []):
            yield from self._function_declarations(child)

    def _function_signature(self, node):
        name = node["children"][0]["value"]
        symbol = None
        if self.context is not None:
            symbol = self.context.symbols.symbol_for_declaration(node["children"][0])
        emitted_name = (
            self.context.generated_names.get(id(symbol), name)
            if self.context is not None and symbol is not None
            else name
        )
        return_type = self.declaration_type(node["children"][1], "void")
        input_decls = self.collect_sections(node["children"][2], "input_declarations")
        output_decls = self.collect_sections(node["children"][2], "output_declarations")
        inout_decls = self.collect_sections(node["children"][2], "input_output_declarations")
        params = [self._format_declarator(var_type, var_name) for var_type, var_name in input_decls]
        params += [self._format_declarator(var_type, var_name, pointer=True) for var_type, var_name in output_decls + inout_decls]
        return return_type, emitted_name, params

    def visit_standard_function_name(self, node):
        self.text += node["value"]

    def visit_derived_function_name(self, node):
        self.text += node["value"]

    def visit_primary_expression(self, node):
        children = node.get("children", [])
        if not children or children[0].get("name") != "function_name":
            self.accept(node)
            return

        standard_name = self._first_named(children[0], "standard_function_name")
        standard_name_value = (
            str(standard_name.get("value", "")).upper()
            if standard_name
            else ""
        )

        if standard_name_value == "LEN_MAX":
            argument = self._first_named(node, "expression")
            length = self._string_max_length(argument)
            if length is not None:
                self.text += str(length)
                return

        trunc_match = re.fullmatch(
            r"(?:(?:REAL|LREAL)_)?TRUNC_(SINT|INT|DINT|LINT|USINT|UINT|UDINT|ULINT)",
            standard_name_value,
        )
        if trunc_match:
            argument = self._first_named(node, "expression")
            self.text += f"(({self.iecType2C(trunc_match.group(1))})({self.render(argument)}))"
            return

        resolved = self.context.resolved_calls.get(id(node)) if self.context is not None else None
        if resolved is not None:
            self.text += self.context.generated_names.get(id(resolved), resolved.name)
        else:
            self.visit(children[0])
        self.text += "("
        resolved_arguments = (
            self.context.resolved_arguments.get(id(node)) if self.context is not None else None
        )
        arguments = resolved_arguments or [
            child for child in children[1:] if child.get("name") == "param_assignment"
        ]
        for index, argument in enumerate(arguments):
            if index:
                self.text += ", "
            if resolved_arguments is not None:
                self.visit(argument)
            else:
                expressions = [child for child in argument.get("children", []) if child.get("name") == "expression"]
                if expressions:
                    self.visit(expressions[-1])
        self.text += ")"

    def visit_function_declaration(self, node):
        name = node["children"][0]["value"]
        native = self.native_implementations.get(name.casefold())
        return_type, emitted_name, params = self._function_signature(node)
        self.current_function = name
        self.current_return_type = return_type

        local_decls = self.collect_sections(node["children"][2], "function_var_decls")

        if node.get("synthetic") and node.get("generated_by") == "enum-conversions":
            self.text += f"/* Automatically generated conversion for enum {node.get('enum_type')}. */\n"
        else:
            self.text += f"/* IEC function: {name}. */\n"
        self.text += f"{return_type} {emitted_name}({', '.join(params) or 'void'})\n{{\n"
        self.indent_inc()
        if return_type != "void":
            self.text += f"{self.indent}{self._format_declarator(return_type, name)} = {{0}};\n"
        for var_type, var_name in local_decls:
            self.text += f"{self.indent}{self._format_declarator(var_type, var_name)} = {{0}};\n"
        if local_decls or return_type != "void":
            self.text += "\n"
        if native is not None:
            self._emit_native_code(native.section("body") or "")
        else:
            self.accept(node, lambda child_name: child_name == "function_body")
        if return_type != "void":
            self.text += f"{self.indent}return {name};\n"
        self.indent_dec()
        self.text += "}\n\n"
        self.current_function = None
        self.current_return_type = None

    def visit_function_block_declaration(self, node):
        name_node = self._first_named(node, "derived_function_block_name")
        if name_node is None:
            return
        name = name_node["value"]
        native = self.native_implementations.get(name.casefold())
        declarations = self._unique_declarations(self._persistent_declarations(node))
        temporaries = self._unique_declarations(self._temporary_declarations(node))
        retained = self._unique_declarations(self._retained_declarations(node))
        initializers = self._declaration_initializers(node)

        self.text += f"/* Persistent state for IEC function block {name}. */\n"
        self.text += f"typedef struct {name} {{\n"
        self.indent_inc()
        for var_type, var_name in declarations:
            self.text += f"{self.indent}{self._format_declarator(var_type, var_name)};\n"
        if not declarations:
            self.text += f"{self.indent}uint8_t _stc_empty;\n"
        self.indent_dec()
        self.text += f"}} {name};\n\n"

        self.text += f"/* Initialize function block {name}. */\n"
        self.text += f"void {name}_setup({name} *self)\n{{\n"
        self.indent_inc()
        self.text += f"{self.indent}memset(self, 0, sizeof(*self));\n"
        for _, field in declarations:
            if field.casefold() in initializers:
                self.text += f"{self.indent}self->{field} = {initializers[field.casefold()]};\n"
        setup = native.section("setup") if native is not None and native.kind == "function_block" else None
        if setup:
            self._emit_native_code(setup)
        self.indent_dec()
        self.text += "}\n\n"

        self._emit_instance_initializers(name, declarations, retained, initializers)

        inouts = self.collect_sections(node, "input_output_declarations")
        parameters = [f"{name} *self"] + [self._format_declarator(var_type, var_name, pointer=True) for var_type, var_name in inouts]
        entrypoint = "loop" if native is not None and native.kind == "function_block" else "step"
        self.text += f"/* Execute one invocation of function block {name}. */\n"
        self.text += f"void {name}_{entrypoint}({', '.join(parameters)})\n{{\n"
        self.indent_inc()
        previous_instance, previous_fields, previous_pointers = self.current_instance, self.current_instance_fields, self.current_pointer_params
        self.current_instance = "self"
        self.current_instance_fields = {field.casefold() for _, field in declarations if field.casefold() not in {item.casefold() for _, item in inouts}}
        self.current_pointer_params = {field.casefold() for _, field in inouts}
        self.text += f"{self.indent}(void)self;\n"
        for var_type, var_name in temporaries:
            self.text += f"{self.indent}{self._format_declarator(var_type, var_name)} = {{0}};\n"
        if temporaries:
            self.text += "\n"
        if native is not None and native.kind == "function_block":
            self._emit_native_code(native.section("loop") or "")
        else:
            self.accept(node, lambda child_name: child_name == "function_block_body")
        self.current_instance, self.current_instance_fields, self.current_pointer_params = previous_instance, previous_fields, previous_pointers
        self.indent_dec()
        self.text += "}\n\n"

    def visit_program_declaration(self, node):
        name_node = self._first_named(node, "program_type_name")
        if name_node is None:
            return
        name = name_node["value"]
        declarations = self._unique_declarations(self._persistent_declarations(node))
        temporaries = self._unique_declarations(self._temporary_declarations(node))
        retained = self._unique_declarations(self._retained_declarations(node))
        initializers = self._declaration_initializers(node)
        self.text += f"/* Persistent state for IEC program {name}. */\n"
        self.text += f"typedef struct {name} {{\n"
        self.indent_inc()
        for var_type, var_name in declarations:
            self.text += f"{self.indent}{self._format_declarator(var_type, var_name)};\n"
        if not declarations:
            self.text += f"{self.indent}uint8_t _stc_empty;\n"
        self.indent_dec()
        self.text += f"}} {name};\n\n"
        self._emit_instance_initializers(name, declarations, retained, initializers)
        self.text += f"/* Execute one scan cycle of IEC program {name}. */\n"
        self.text += f"void {name}_run({name} *self)\n{{\n"
        self.indent_inc()
        previous_instance, previous_fields, previous_pointers = self.current_instance, self.current_instance_fields, self.current_pointer_params
        self.current_instance, self.current_instance_fields = "self", {field.casefold() for _, field in declarations}
        self.text += f"{self.indent}(void)self;\n"
        for var_type, var_name in temporaries:
            self.text += f"{self.indent}{self._format_declarator(var_type, var_name)} = {{0}};\n"
        if temporaries:
            self.text += "\n"
        self.accept(node, lambda child_name: child_name == "function_block_body")
        self.current_instance, self.current_instance_fields, self.current_pointer_params = previous_instance, previous_fields, previous_pointers
        self.indent_dec()
        self.text += "}\n\n"

    def visit_action(self, node):
        name_node = self._first_named(node, "action_name")
        if name_node is None:
            return
        self.text += f"/* IEC action: {name_node['value']}. */\n"
        self.text += f"void {name_node['value']}(void)\n{{\n"
        self.indent_inc()
        self.accept(node, lambda child_name: child_name == "function_block_body")
        self.indent_dec()
        self.text += "}\n\n"

    def visit_simple_type_declaration(self, node):
        name = self._first_named(node, "simple_type_name")
        array = self._first_named(node, "array_specification")
        structure = self._first_named(node, "structure_declaration")
        if name and array:
            self._emit_array_type(name["value"], array)
        elif name and structure:
            self._emit_structure_type(name["value"], structure)
        elif name:
            underlying = next(
                (self.iecType2C(item.get("value")) for item in self._named_nodes(node, "signed_integer_type_name") + self._named_nodes(node, "unsigned_integer_type_name") + self._named_nodes(node, "real_type_name") + self._named_nodes(node, "bit_string_type_name") if item.get("value")),
                "int16_t",
            )
            self.text += f"typedef {underlying} {name['value']};\n"

    def visit_data_type_declaration(self, node):
        if self._types_pre_emitted:
            return
        for declaration in self._named_nodes(node, "simple_type_declaration"):
            self.visit_simple_type_declaration(declaration)
        for declaration in self._named_nodes(node, "subrange_type_declaration"):
            self.visit_subrange_type_declaration(declaration)
        for declaration in self._named_nodes(node, "enumerated_type_declaration"):
            self.visit_enumerated_type_declaration(declaration)
        for declaration in self._named_nodes(node, "array_type_declaration"):
            self.visit_array_type_declaration(declaration)
        for declaration in self._named_nodes(node, "structure_type_declaration"):
            self.visit_structure_type_declaration(declaration)
        for declaration in self._named_nodes(node, "string_type_declaration"):
            self.visit_string_type_declaration(declaration)

    def visit_subrange_type_declaration(self, node):
        name = self._first_named(node, "subrange_type_name")
        if name:
            underlying = next(
                (self.iecType2C(item.get("value")) for item in self._named_nodes(node, "signed_integer_type_name") + self._named_nodes(node, "unsigned_integer_type_name") if item.get("value")),
                "int16_t",
            )
            self.text += f"typedef {underlying} {name['value']};\n"

    def visit_enumerated_type_declaration(self, node):
        name = self._first_named(node, "enumerated_type_name")
        values = [item["value"] for item in self._named_nodes(node, "enumerated_value") if item.get("value")]
        if name and values:
            self.text += f"typedef enum {name['value']} {{\n"
            for index, value in enumerate(values):
                comma = "," if index < len(values) - 1 else ""
                self.text += f"    {value}{comma}\n"
            self.text += f"}} {name['value']};\n"

    def visit_array_type_declaration(self, node):
        name = self._first_named(node, "array_type_name")
        spec = self._first_named(node, "array_specification")
        if name and spec:
            self._emit_array_type(name["value"], spec)

    def _emit_array_type(self, name, spec):
        sizes = self._array_dimensions(spec)
        element = self.declaration_type(spec)
        self.text += f"typedef {element} {name}{sizes};\n"

    def visit_string_type_declaration(self, node):
        name = self._first_named(node, "string_type_name")
        size = next((self.render(item) for item in self._named_nodes(node, "integer")), "80")
        if name:
            self.text += f"typedef char {name['value']}[{size} + 1];\n"

    def visit_structure_type_declaration(self, node):
        name = self._first_named(node, "structure_type_name")
        if not name:
            return
        self._emit_structure_type(name["value"], node)

    def _emit_structure_type(self, name, node):
        self.text += f"typedef struct {name} {{\n"
        self.indent_inc()
        for element in self._named_nodes(node, "structure_element_declaration"):
            field = self._first_named(element, "structure_element_name")
            if field:
                self.text += f"{self.indent}{self._format_declarator(self._declaration_type(element), field['value'])};\n"
        self.indent_dec()
        self.text += f"}} {name};\n"

    def _named_nodes(self, node, name):
        result = []
        if not isinstance(node, dict):
            return result
        if node.get("name") == name:
            result.append(node)
        for child in node.get("children", []):
            result.extend(self._named_nodes(child, name))
        return result

    def _emit_native_code(self, source):
        for line in source.splitlines():
            self.text += f"{self.indent}{line.rstrip()}\n" if line.strip() else "\n"

    def _first_named(self, node, name):
        if not isinstance(node, dict):
            return None
        if node.get("name") == name:
            return node
        for child in node.get("children", []):
            found = self._first_named(child, name)
            if found is not None:
                return found
        return None

    def visit_var1_init_decl(self, node):
        var_type = self.extract_type(node) or "int16_t"
        names = [child["value"] for child in node["children"][0]["children"]]
        self.text += f"{var_type} {', '.join(names)}"

    def visit_expression(self, node):
        separator = " | " if self._is_bitwise_expression(node) else " || "
        self._join_children(node, separator, parenthesize_operands=True)

    def visit_xor_expression(self, node):
        self._join_children(node, " ^ ", parenthesize_operands=True)

    def visit_and_expression(self, node):
        separator = " & " if self._is_bitwise_expression(node) else " && "
        self._join_children(node, separator, parenthesize_operands=True)

    def _is_bitwise_expression(self, node):
        bit_types = {"uint8_t", "uint16_t", "uint32_t", "uint64_t"}
        own_type = self.c_type_for_node(node)
        if own_type in bit_types:
            return True
        descendant_types = {
            self.c_type_for_node(item)
            for item in self._named_nodes(node, "variable_name")
        }
        return bool(descendant_types & bit_types) and "bool" not in descendant_types

    def visit_comparison(self, node):
        children = node.get("children", [])
        if len(children) == 3 and children[1].get("name") == "comparison_equality_operator":
            left, operator, right = children
            left_text, right_text = self.render(left), self.render(right)
            string_comparison = (
                self.c_type_for_node(left) == "const char *"
                or self.c_type_for_node(right) == "const char *"
                or left_text.startswith('"')
                or right_text.startswith('"')
            )
            if string_comparison:
                relation = "!=" if operator.get("value") in {"NEQ", "<>"} else "=="
                self.text += f"strcmp({left_text}, {right_text}) {relation} 0"
                return
        self._visit_infix(node)

    def visit_comparison_equality_operator(self, node):
        op = {"=": "==", "NEQ": "!=", "<>": "!="}.get(node["value"], node["value"])
        self.text += f" {op} "

    def visit_equ_expression(self, node):
        self._visit_infix(node)

    def visit_add_expression(self, node):
        self._visit_infix(node)

    def visit_term(self, node):
        self._visit_infix_from_child_value(node)

    def visit_power_expression(self, node):
        children = [child for child in node.get("children", []) if isinstance(child, dict)]
        if len(children) == 1:
            self.visit(children[0])
        elif len(children) >= 2:
            # IEC exponentiation is right-associative: a ** b ** c is
            # equivalent to a ** (b ** c).
            expression = self.render(children[-1])
            for child in reversed(children[:-1]):
                expression = f"pow({self.render(child)}, {expression})"
            self.text += expression

    def visit_unary_expression(self, node):
        op = node.get("value")
        if not op:
            self.accept(node)
            return
        child = next((item for item in node.get("children", []) if isinstance(item, dict)), None)
        symbol = ("~" if child is not None and self._is_bitwise_expression(child) else "!") if op == "NOT" else op
        self.text += f"({symbol}("
        self.accept(node)
        self.text += "))"

    def visit_add_operator(self, node):
        self.text += f" {node['value']} "

    def visit_comparison_operator(self, node):
        op = {"LE_EQ": "<=", "GE_EQ": ">="}.get(node["value"], node["value"])
        self.text += f" {op} "

    def visit_assignment_statement(self, node):
        self.text += self.indent
        self.accept(node, lambda name: name == "variable")
        self.text += " = "
        self.accept(node, lambda name: name == "expression")
        self.text += ";\n"

    def visit_assert_statement(self, node):
        expression = next(child for child in node.get("children", []) if isinstance(child, dict))
        self.text += f"{self.indent}ASSERT({self.render(expression)});\n"

    def visit_exit_statement(self, node):
        self.text += f"{self.indent}break;\n"

    def visit_if_statement(self, node):
        self.text += self.indent + "if ("
        self.visit(node["children"][0])
        self.text += ") {\n"
        self.indent_inc()
        self.visit(node["children"][1])
        self.indent_dec()
        self.text += self.indent + "}\n"
        self.accept(node, lambda name: name == "elseif_statement_list")
        self.accept(node, lambda name: name == "else_statement")

    def visit_elseif_statement(self, node):
        self.text += self.indent + "else if ("
        self.visit(node["children"][0])
        self.text += ") {\n"
        self.indent_inc()
        self.visit(node["children"][1])
        self.indent_dec()
        self.text += self.indent + "}\n"

    def visit_else_statement(self, node):
        self.text += self.indent + "else {\n"
        self.indent_inc()
        self.accept(node)
        self.indent_dec()
        self.text += self.indent + "}\n"

    def visit_while_statement(self, node):
        self.text += self.indent + "while ("
        self.visit(node["children"][0])
        self.text += ") {\n"
        self.indent_inc()
        self.visit(node["children"][1])
        self.indent_dec()
        self.text += self.indent + "}\n"

    def visit_repeat_statement(self, node):
        self.text += self.indent + "do {\n"
        self.indent_inc()
        self.visit(node["children"][0])
        self.indent_dec()
        self.text += self.indent + "} while (!("
        self.visit(node["children"][1])
        self.text += "));\n"

    def visit_token(self, node):
        self.text += str(node.get("value", ""))

    def visit_control_variable(self, node):
        value = next((child.get("value") for child in node.get("children", []) if isinstance(child, dict)), "")
        if self.current_instance is not None and isinstance(value, str) and value.casefold() in self.current_instance_fields:
            self.text += f"{self.current_instance}->{value}"
        elif isinstance(value, str) and value.casefold() in self.current_pointer_params:
            self.text += f"(*{value})"
        else:
            self.accept(node)

    def visit_for_statement(self, node):
        control, for_list, body = node["children"][:3]
        parts = [child for child in for_list.get("children", []) if isinstance(child, dict)]
        start = parts[0]
        direction = str(parts[1].get("value", "TO")).upper() if len(parts) > 1 else "TO"
        end = parts[2] if len(parts) > 2 else parts[-1]
        by = parts[4] if len(parts) > 4 and parts[3].get("value") == "BY" else None
        variable = self.render(control)
        start_text = self.render(start)
        end_text = self.render(end)
        comparator = ">=" if direction == "DOWNTO" else "<="
        if by is None:
            step = f"{variable}--" if direction == "DOWNTO" else f"{variable}++"
        else:
            operator = "-=" if direction == "DOWNTO" else "+="
            step = f"{variable} {operator} {self.render(by)}"
        self.text += self.source_line_directive(node)
        self.text += f"{self.indent}for ({variable} = {start_text}; {variable} {comparator} {end_text}; {step}) {{\n"
        self.indent_inc()
        self.visit(body)
        self.indent_dec()
        self.text += f"{self.indent}}}\n"

    def visit_case_statement(self, node):
        children = node.get("children", [])
        expression = next(child for child in children if child.get("name") == "expression")
        expression_text = self.render(expression)
        self.text += self.source_line_directive(node)
        emitted = False
        default_statements = None
        for child in children:
            if child.get("name") == "case_element":
                case_list = next(item for item in child["children"] if item.get("name") == "case_list")
                statements = next(item for item in child["children"] if item.get("name") == "statement_list")
                conditions = []
                for label in (item for item in case_list.get("children", []) if item.get("name") == "case_list_element"):
                    subrange = self._first_named(label, "subrange")
                    if subrange is not None:
                        bounds = self._named_nodes(subrange, "signed_integer")
                        if len(bounds) == 2:
                            conditions.append(f"(({expression_text}) >= ({self.render(bounds[0])}) && ({expression_text}) <= ({self.render(bounds[1])}))")
                    else:
                        conditions.append(f"({expression_text}) == ({self.render(label)})")
                keyword = "if" if not emitted else "else if"
                self.text += f"{self.indent}{keyword} ({' || '.join(conditions) or 'false'}) {{\n"
                self.indent_inc()
                self.visit(statements)
                self.indent_dec()
                self.text += f"{self.indent}}}\n"
                emitted = True
            elif child.get("name") == "statement_list":
                default_statements = child
        if default_statements is not None:
            self.text += f"{self.indent}{'else ' if emitted else ''}{{\n"
            self.indent_inc()
            self.visit(default_statements)
            self.indent_dec()
            self.text += f"{self.indent}}}\n"

    def visit_case_element(self, node):
        case_list = next(child for child in node["children"] if child.get("name") == "case_list")
        statements = next(child for child in node["children"] if child.get("name") == "statement_list")
        labels = [child for child in case_list.get("children", []) if child.get("name") == "case_list_element"]
        for label in labels:
            self.text += f"{self.indent}case {self.render(label)}:\n"
        self.indent_inc()
        self.visit(statements)
        self.text += f"{self.indent}break;\n"
        self.indent_dec()

    def visit_fb_invocation(self, node):
        self.text += f"{self.indent}(void)0;\n"

    def visit_configuration_declaration(self, node):
        name_node = self._first_named(node, "configuration_name")
        if name_node is None:
            return
        name = name_node["value"]
        tasks = {}
        for task in self._named_nodes(node, "task_configuration"):
            task_name_node = self._first_named(task, "task_name")
            if task_name_node is None:
                continue
            initialization = self._first_named(task, "task_initialization")
            values = [str(value).upper() for value in self._raw_values(initialization)] if initialization else []
            duration = self._first_named(initialization, "duration") if initialization else None
            interval = int(self.render(duration)) if duration is not None else 1
            integers = self._named_nodes(initialization, "integer") if initialization else []
            priority = int(str(integers[-1].get("value", "0")).replace("_", "")) if integers else 0
            tasks[task_name_node["value"].casefold()] = {
                "name": task_name_node["value"], "interval": max(interval, 1), "priority": priority,
                "single": "SINGLE" in values,
            }

        programs = []
        for program in self._named_nodes(node, "program_configuration"):
            instance_node = self._first_named(program, "program_name")
            type_node = self._first_named(program, "program_type_name")
            if instance_node is None or type_node is None:
                continue
            task_node = self._first_named(program, "task_name")
            tokens = {value.upper() for value in self._raw_values(program)}
            programs.append({
                "instance": instance_node["value"], "type": type_node["value"],
                "task": task_node["value"].casefold() if task_node else None,
                "retain": "RETAIN" in tokens, "non_retain": "NON_RETAIN" in tokens,
            })

        self.text += f"/* IEC configuration {name}. */\n"
        self.text += "/* Persistent program instances. Each instance owns independent scan state. */\n"
        for program in programs:
            self.text += f"{program['type']} {name}_{program['instance']};\n"
        if tasks:
            self.text += "\n/* Elapsed-time accumulators used by cyclic tasks. */\n"
        for task in tasks.values():
            self.text += f"static uint64_t {name}_{task['name']}_elapsed_ms;\n"
        self.text += "\n"

        self.text += "/* Initialize every program instance and scheduler for a cold start. */\n"
        self.text += f"void {name}_cold_start(void)\n{{\n"
        for program in programs:
            self.text += f"    {program['type']}_cold_init(&{name}_{program['instance']});\n"
        for task in tasks.values():
            self.text += f"    {name}_{task['name']}_elapsed_ms = 0;\n"
        self.text += "}\n\n"

        self.text += "/* Restart execution while preserving retentive program state. */\n"
        self.text += f"void {name}_warm_start(void)\n{{\n"
        for program in programs:
            target = f"{name}_{program['instance']}"
            if program["retain"]:
                continue
            if program["non_retain"]:
                self.text += f"    {program['type']}_cold_init(&{target});\n"
            else:
                self.text += f"    {program['type']}_warm_init(&{target});\n"
        for task in tasks.values():
            self.text += f"    {name}_{task['name']}_elapsed_ms = 0;\n"
        self.text += "}\n\n"

        self.text += "/* Return the shortest configured cyclic-task interval. */\n"
        self.text += f"uint64_t {name}_base_interval_ms(void)\n{{\n"
        base_interval = min((task["interval"] for task in tasks.values()), default=1)
        self.text += f"    return UINT64_C({base_interval});\n}}\n\n"

        self.text += "/* Advance the scheduler while preserving chronological task order. */\n"
        self.text += f"void {name}_cycle(uint64_t elapsed_ms)\n{{\n"
        for program in programs:
            if program["task"] is None:
                self.text += f"    {program['type']}_run(&{name}_{program['instance']});\n"

        scheduled_tasks = sorted(
            tasks.values(),
            key=lambda item: (item["priority"], item["name"].casefold()),
        )

        if scheduled_tasks:
            self.text += "    uint64_t remaining_ms = elapsed_ms;\n"

            for task in scheduled_tasks:
                if task["single"]:
                    self.text += f"    bool {name}_{task['name']}_fired = false;\n"

            self.text += "    while (remaining_ms > 0) {\n"
            self.text += "        uint64_t next_due_ms = UINT64_MAX;\n"

            for task in tasks.values():
                elapsed_name = f"{name}_{task['name']}_elapsed_ms"
                interval = task["interval"]
                if task["single"]:
                    self.text += f"        if (!{name}_{task['name']}_fired) {{\n"
                    indent = "            "
                else:
                    indent = "        "
                self.text += (
                    f"{indent}uint64_t until_due_ms = "
                    f"UINT64_C({interval}) - {elapsed_name};\n"
                )
                self.text += (
                    f"{indent}if (until_due_ms < next_due_ms) "
                    "next_due_ms = until_due_ms;\n"
                )
                if task["single"]:
                    self.text += "        }\n"

            self.text += "        if (next_due_ms > remaining_ms) {\n"
            for task in tasks.values():
                elapsed_name = f"{name}_{task['name']}_elapsed_ms"
                if task["single"]:
                    self.text += (
                        f"            if (!{name}_{task['name']}_fired) "
                        f"{elapsed_name} += remaining_ms;\n"
                    )
                else:
                    self.text += f"            {elapsed_name} += remaining_ms;\n"
            self.text += "            break;\n"
            self.text += "        }\n"

            for task in tasks.values():
                elapsed_name = f"{name}_{task['name']}_elapsed_ms"
                if task["single"]:
                    self.text += (
                        f"        if (!{name}_{task['name']}_fired) "
                        f"{elapsed_name} += next_due_ms;\n"
                    )
                else:
                    self.text += f"        {elapsed_name} += next_due_ms;\n"
            self.text += "        remaining_ms -= next_due_ms;\n"

            for task in scheduled_tasks:
                assigned = [
                    program for program in programs
                    if program["task"] == task["name"].casefold()
                ]
                elapsed_name = f"{name}_{task['name']}_elapsed_ms"
                interval = task["interval"]
                condition = f"{elapsed_name} >= UINT64_C({interval})"
                if task["single"]:
                    condition = f"!{name}_{task['name']}_fired && ({condition})"
                self.text += f"        if ({condition}) {{\n"
                self.text += f"            {elapsed_name} -= UINT64_C({interval});\n"
                for program in assigned:
                    self.text += (
                        f"            {program['type']}_run("
                        f"&{name}_{program['instance']});\n"
                    )
                if task["single"]:
                    self.text += f"            {elapsed_name} = 0;\n"
                    self.text += f"            {name}_{task['name']}_fired = true;\n"
                self.text += "        }\n"

            self.text += "    }\n"

        self.text += "}\n\n"

    def _join_children(self, node, separator, parenthesize_operands=False):
        children = node["children"]
        wrap = parenthesize_operands and len(children) > 1
        for index, child in enumerate(children):
            if index:
                self.text += separator
            if wrap:
                self.text += "("
            self.visit(child)
            if wrap:
                self.text += ")"

    def _visit_infix(self, node):
        for child in node["children"]:
            self.visit(child)

    def _visit_infix_from_child_value(self, node):
        children = node["children"]
        if not children:
            return
        self.visit(children[0])
        for child in children[1:]:
            op = {"MOD": "%"}.get(child.get("value"), child.get("value"))
            self.text += f" {op} "
            if op == "%":
                self.text += "((int64_t)("
                self.visit(child)
                self.text += "))"
            else:
                self.visit(child)
